version: "3.9"

services:
  app:
    build: .
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
      - /app/node_modules
