apiVersion: v1
kind: Secret
metadata:
  name: helpninja-secrets
  namespace: helpninja
type: Opaque
stringData:
  # These will be populated by the deployment script
  OPENAI_API_KEY: "SECRET_PLACEHOLDER"
  OPENAI_CHAT_MODEL: "gpt-4o-mini"
  OPENAI_EMBED_MODEL: "text-embedding-3-small"
  DATABASE_URL: "SECRET_PLACEHOLDER"
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  STRIPE_PRICE_STARTER: ""
  STRIPE_PRICE_PRO: ""
  STRIPE_PRICE_AGENCY: ""
  SUPABASE_SERVICE_ROLE_KEY: ""
  SLACK_WEBHOOK_URL: ""
  RESEND_API_KEY: "SECRET_PLACEHOLDER"
  CLERK_WEBHOOK_SECRET: "SECRET_PLACEHOLDER"
  CLERK_SECRET_KEY: "SECRET_PLACEHOLDER"
  CLERK_PUBLISHABLE_KEY: "PUBLIC_PLACEHOLDER"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "PUBLIC_PLACEHOLDER"
