name: Deploy to Azure Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: helpninja

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        build-args: |
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Install kubelogin
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: v0.0.25

    - name: Set AKS Context with admin access
      uses: azure/aks-set-context@v4
      with:
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        admin: true

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: |
        # Extract the short tag from metadata output
        SHORT_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -o 'main-[a-f0-9]\{7\}' | head -1)
        IMAGE_FULL="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${SHORT_TAG}"
        echo "Deploying with image: ${IMAGE_FULL}"

        # Create namespace first
        kubectl apply -f ./k8s/namespace.yaml

        # Replace placeholders in YAML files with actual values
        echo "=== UPDATING CONFIGURATION ==="

        # Update deployment with correct image
        sed "s|IMAGE_PLACEHOLDER|${IMAGE_FULL}|g" ./k8s/deployment.yaml > /tmp/deployment.yaml

        # Update configmap with Supabase URL and Clerk URLs from repo variables
        sed -e "s|SUPABASE_URL_PLACEHOLDER|${{ vars.NEXT_PUBLIC_SUPABASE_URL }}|g" \
            -e "s|SUPABASE_ANON_KEY_PLACEHOLDER|${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}|g" \
            -e "s|STRIPE_PUBLISHABLE_KEY_PLACEHOLDER|${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}|g" \
            -e "s|CLERK_PUBLISHABLE_KEY_PLACEHOLDER|${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}|g" \
            -e "s|SITE_URL_PLACEHOLDER|${{ vars.SITE_URL }}|g" \
            -e "s|CLERK_SIGN_IN_URL_PLACEHOLDER|${{ vars.CLERK_SIGN_IN_URL }}|g" \
            -e "s|CLERK_SIGN_UP_URL_PLACEHOLDER|${{ vars.CLERK_SIGN_UP_URL }}|g" \
            -e "s|NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL_PLACEHOLDER|${{ vars.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }}|g" \
            -e "s|NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL_PLACEHOLDER|${{ vars.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }}|g" \
            -e "s|CLERK_SIGN_IN_FALLBACK_REDIRECT_URL_PLACEHOLDER|${{ vars.CLERK_SIGN_IN_FALLBACK_REDIRECT_URL }}|g" \
            -e "s|CLERK_SIGN_UP_FALLBACK_REDIRECT_URL_PLACEHOLDER|${{ vars.CLERK_SIGN_UP_FALLBACK_REDIRECT_URL }}|g" \
            -e "s|CLERK_SIGN_IN_FORCE_REDIRECT_URL_PLACEHOLDER|${{ vars.CLERK_SIGN_IN_FORCE_REDIRECT_URL }}|g" \
            -e "s|CLERK_SIGN_UP_FORCE_REDIRECT_URL_PLACEHOLDER|${{ vars.CLERK_SIGN_UP_FORCE_REDIRECT_URL }}|g" \
            ./k8s/configmap.yaml > /tmp/configmap.yaml

        # Create secrets using kubectl (more reliable than YAML placeholders)
        echo "=== CREATING SECRETS ==="
        kubectl create secret generic helpninja-secrets \
          --namespace=helpninja \
          --from-literal=OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
          --from-literal=OPENAI_CHAT_MODEL="${{ vars.OPENAI_CHAT_MODEL }}" \
          --from-literal=OPENAI_EMBED_MODEL="${{ vars.OPENAI_EMBED_MODEL }}" \
          --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --from-literal=STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
          --from-literal=CLERK_WEBHOOK_SECRET="${{ secrets.CLERK_WEBHOOK_SECRET }}" \
          --from-literal=CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}" \
          --from-literal=NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" \
          --from-literal=STRIPE_PRICE_STARTER_MONTHLY="${{ vars.STRIPE_PRICE_STARTER_MONTHLY }}" \
          --from-literal=STRIPE_PRICE_STARTER_YEARLY="${{ vars.STRIPE_PRICE_STARTER_YEARLY }}" \
          --from-literal=STRIPE_PRICE_PRO_MONTHLY="${{ vars.STRIPE_PRICE_PRO_MONTHLY }}" \
          --from-literal=STRIPE_PRICE_PRO_YEARLY="${{ vars.STRIPE_PRICE_PRO_YEARLY }}" \
          --from-literal=STRIPE_PRICE_AGENCY_MONTHLY="${{ vars.STRIPE_PRICE_AGENCY_MONTHLY }}" \
          --from-literal=STRIPE_PRICE_AGENCY_YEARLY="${{ vars.STRIPE_PRICE_AGENCY_YEARLY }}" \
          --from-literal=STRIPE_STARTER_PRODUCT_ID="${{ vars.STRIPE_STARTER_PRODUCT_ID }}" \
          --from-literal=STRIPE_PRO_PRODUCT_ID="${{ vars.STRIPE_PRO_PRODUCT_ID }}" \
          --from-literal=STRIPE_AGENCY_PRODUCT_ID="${{ vars.STRIPE_AGENCY_PRODUCT_ID }}" \
          --from-literal=SLACK_WEBHOOK_URL="${{ vars.SLACK_WEBHOOK_URL }}" \
          --from-literal=RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
          --from-literal=SUPPORT_FROM_EMAIL="${{ vars.SUPPORT_FROM_EMAIL }}" \
          --from-literal=SUPPORT_FALLBACK_TO_EMAIL="${{ vars.SUPPORT_FALLBACK_TO_EMAIL }}" \
          --dry-run=client -o yaml | kubectl apply -f -

        # Apply all Kubernetes resources
        echo "=== DEPLOYING RESOURCES ==="
        kubectl apply -f /tmp/configmap.yaml
        kubectl apply -f /tmp/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
        kubectl apply -f ./k8s/ingress.yaml
        kubectl apply -f ./k8s/hpa.yaml

        # Wait for deployment to be ready
        echo "=== WAITING FOR DEPLOYMENT ==="
        kubectl rollout status deployment/helpninja -n helpninja --timeout=300s

        echo "Deployment completed successfully!"

    - name: Verify deployment
      run: |
        echo "Verifying production deployment..."
        kubectl get namespace helpninja
        kubectl get pods -n helpninja
        kubectl get svc -n helpninja
        kubectl get ingress -n helpninja

    - name: Check deployments
      run: |
        echo "Checking production deployment status..."
        kubectl get deployments -n helpninja
        kubectl describe deployment helpninja -n helpninja

    - name: Health check
      run: |
        echo "Performing health check..."
        kubectl wait --for=condition=available --timeout=300s deployment/helpninja -n helpninja
        echo "Production deployment is ready and healthy!"
